### ISSUE TITLE
Estrarre tutti i simboli da una sorgente remota

### ISSUE THREAD

**Issue by uazo** [frabert/ClangQL#1]
Salve Francesco,
mi permetto di scrivere in italiano, spero non sia un problema.
Innanzitutto, complimenti per il progetto!
Mi chiedevo se esiste la possibilità di estrarre tutti i simboli dal una sorgente remota, ho notato che il `count(*)` della tabella restituisce 9998 righe, mi chiedevo se per caso è un limite del server o del client.
Questo è quello che vorrei fare:

```
.load clangql
CREATE VIRTUAL TABLE llvm_symbols USING clangql (symbols, android.clangd-index.chromium.org:5900);
CREATE VIRTUAL TABLE llvm_base_of USING clangql (base_of, android.clangd-index.chromium.org:5900);
CREATE VIRTUAL TABLE llvm_overridden_by USING clangql (overridden_by, android.clangd-index.chromium.org:5900);
CREATE VIRTUAL TABLE llvm_refs USING clangql (refs, android.clangd-index.chromium.org:5900);

.headers on
.mode csv
.output c:/temp/symbols.txt
SELECT * FROM llvm_symbols;
```
grazie mille in anticipo.

**Comment by frabert** [comment]
Salve!
Il client non fa alcuna richiesta specifica al server riguardo ad un possibile limite sul numero di risultati da restituire, per cui mi viene da pensare che sia un modo per salvaguardare il carico lato server (in effetti un'orda di client che richiedono tutti i simboli di Chromium contemporaneamente suona molto vicina ad un DDoS :) )

Non ho letto il codice del server, ma ipotizzerei che il limite delle ~1000 righe sia configurabile dal loro lato.

Non è una soluzione nè molto elegante nè probabilmente efficiente, però forse facento una cosa tipo

    SELECT DISTINCT * FROM llvm_symbols WHERE Name LIKE "a" OR Name LIKE "b" OR ...

dovrebbe forzare SQLite a fare richieste separate che potrebbero rientrare nel limite delle 10000 ciascuna, per poi riunirle tutte.

**Comment by uazo** [comment]
Grazie per la veloce risposta!
Purtroppo anche così il limite viene superato... cercherò qualche altro workaround.

> il limite delle ~1000 righe sia configurabile dal loro lato.

L'ho pensato anch'io: proverò a creare un mio indice.

La disturbo per un'ultima domanda: secondo lei come mai una ricerca per
```
SELECT * FROM llvm_symbols WHERE type = "c:$@N@base@S@Feature";
```
non è in grado di estrarre tutti i risultati?

**Comment by frabert** [comment]
Le uniche query che il server supporta sono quelle per nome e per scope (eventualmente fuzzy), per cui SQLite tenta di eseguire la richiesta facendo il download totale delle righe, che però rientra nella limitazione già notata.

Purtroppo l'API esposta dal server è piuttosto limitata. Da qualche tempo ho in mente di provare a sostituire l'attuale metodo di storage di clangd con sqlite stesso per avere a disposizione un database su cui fare query direttamente, ma non ho ancora trovato il tempo...

**Comment by uazo** [comment]
> Le uniche query che il server supporta sono quelle per nome e per scope 

Grazie, volevo una conferma, l'ho letto nel readme.

> Da qualche tempo ho in mente di provare a sostituire l'attuale metodo di storage di clangd con sqlite stesso per avere a disposizione un database su cui fare query direttamente

purtroppo non conosco (ancora :) clangd, quindi, sinceramente, non so di cosa parla :)
mi sono iscritto alla sua repo, la seguirò attentamente! 

> ma non ho ancora trovato il tempo...

E' una cosa in comune...

Grazie mille per la disponibilità.
